config/routes.rb
Templater::Application.routes.draw do
  resources :users

  resources :sql_templates
  
  match "cms/*page", :to => "cms#respond"

  root :to => "cms#welcome"

end

app/models/sql_template.rb
class SqlTemplate < ActiveRecord::Base
  validates :body, :path, :presence => true
  
  validates :format, :inclusion => Mime::SET.symbols.map(&:to_s)
  validates :locale, :inclusion => I18n.available_locales.map(&:to_s)
  validates :handler, :inclusion => 
    ActionView::Template::Handlers.extensions.map(&:to_s)
      
  after_save do
    SqlTemplate::Resolver.instance.clear_cache
  end
  
  class Resolver < ActionView::Resolver
    require "singleton"
    include Singleton
    
    protected
    
    def find_templates(name, prefix, partial, details)
      conditions = {
        :path => normalize_path(name, prefix),
        :locale => normalize_array(details[:locale]).first,
        :format => normalize_array(details[:formats]).first,
        :handler => normalize_array(details[:handlers]).first,
        :partial => partial || false
      }
      ::SqlTemplate.where(conditions).map do |record|
        initialize_template(record)
      end
    end
    
    # Normalize name and prefix, so the tuple ["indes, "users] becomes
    # "user/index" and the tuple ["template", nil] becomes "template".
    def normalize_path(name, prefix)
      prefix.present? ? "#{prefix}/#{name}" : name
    end
    
    # Normalize arrays by converting all symbols to strings.
    def normalize_array(array)
      array.map(&:to_s)
    end
    
    # Initialize an ActionView::Template object based on the record found.
    def initialize_template(record)
      source = record.body
      identifier = "SqlTemplate - #{record.id} - #{record.path.inspect}"
      handler = ActionView::Template.registered_template_handler(record.handler)
      
      details = {
        :format => Mime[record.format],
        :updated_at => record.updated_at,
        :virtual_path => virtual_path(record.path, record.partial)
      }
      
      ActionView::Template.new(source, identifier, handler, details)
    end
      
    # Make paths as "users/user" become "user/_user" for partials.
    def virtual_path(path, partial)
      return path unless partial
      if index = path.rindex("/")
        path.insert(index + 1, "_")
      else
        "_#{path}"
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  include AbstractController::Layouts
  include ActionController::Rendering
  include AbstractController::Helpers
  
  append_view_path SqlTemplate::Resolver.instance
  helper CmsHelper
  
  def welcome
    respond
  end
  
  def respond
    render :template => params[:page]
  end
end

app/controllers/sql_templates_controller.rb
class SqlTemplatesController < ApplicationController
  append_view_path SqlTemplate::Resolver.instance
  layout 'sql_template'
  
  # GET /sql_templates
  # GET /sql_templates.xml
  def index
    @sql_templates = SqlTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sql_templates }
    end
  end

  # GET /sql_templates/1
  # GET /sql_templates/1.xml
  def show
    @sql_template = SqlTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sql_template }
    end
  end

  # GET /sql_templates/new
  # GET /sql_templates/new.xml
  def new
    @sql_template = SqlTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sql_template }
    end
  end

  # GET /sql_templates/1/edit
  def edit
    @sql_template = SqlTemplate.find(params[:id])
  end

  # POST /sql_templates
  # POST /sql_templates.xml
  def create
    @sql_template = SqlTemplate.new(params[:sql_template])

    respond_to do |format|
      if @sql_template.save
        format.html { redirect_to(@sql_template, :notice => 'Sql template was successfully created.') }
        format.xml  { render :xml => @sql_template, :status => :created, :location => @sql_template }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sql_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sql_templates/1
  # PUT /sql_templates/1.xml
  def update
    @sql_template = SqlTemplate.find(params[:id])

    respond_to do |format|
      if @sql_template.update_attributes(params[:sql_template])
        format.html { redirect_to(@sql_template, :notice => 'Sql template was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sql_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sql_templates/1
  # DELETE /sql_templates/1.xml
  def destroy
    @sql_template = SqlTemplate.find(params[:id])
    @sql_template.destroy

    respond_to do |format|
      format.html { redirect_to(sql_templates_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  append_view_path SqlTemplate::Resolver.instance
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/helpers/sql_templates_helper.rb
module SqlTemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<title>Template Generator</title>

  	<%= stylesheet_link_tag "application" %>

  	<%= javascript_include_tag :defaults %>
  	<%= csrf_meta_tag %>
	<%= yield(:head) %>	
</head>
<body>
	<section id="container">
		<header>
			<h1><%= link_to "CMS Template Engine", root_path %></h1>

			<nav>
				<ul>
					<li><%= link_to "Home", root_path %></a></li>
					<li><%= link_to "Templates", sql_templates_path %></a></li>
				</ul>
			</nav>

		</header>

		<section id="main-content">
			<%= yield %>
		</section>

		<section id="subnav">
		</section>
	</section>
</body>
</html>

app/views/sql_templates/_form.html.erb
<%= form_for(@sql_template) do |f| %>
  <% if @sql_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sql_template.errors.count, "error") %> prohibited this sql_template from being saved:</h2>

      <ul>
      <% @sql_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :format %><br />
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :locale %><br />
    <%= f.text_field :locale %>
  </div>
  <div class="field">
    <%= f.label :handler %><br />
    <%= f.text_field :handler %>
  </div>
  <div class="field">
    <%= f.label :partial %><br />
    <%= f.check_box :partial %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sql_templates/edit.html.erb
<h1>Editing sql_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @sql_template %> |
<%= link_to 'Back', sql_templates_path %>

app/views/sql_templates/index.html.erb
<h1>Templates</h1>

<table>
  <tr>
    <th>Path</th>
    <th>Format</th>
    <th>Locale</th>
    <th>Handler</th>
    <th>Partial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sql_templates.each do |sql_template| %>
  <tr>
    <td><%= sql_template.path %></td>
    <td><%= sql_template.format %></td>
    <td><%= sql_template.locale %></td>
    <td><%= sql_template.handler %></td>
    <td><%= sql_template.partial %></td>
    <td><%= link_to 'Show', sql_template %></td>
    <td><%= link_to 'Edit', edit_sql_template_path(sql_template) %></td>
    <td><%= link_to 'Destroy', sql_template, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sql template', new_sql_template_path %>

app/views/sql_templates/new.html.erb
<h1>New sql_template</h1>

<%= render 'form' %>

<%= link_to 'Back', sql_templates_path %>

app/views/sql_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @sql_template.path %>
</p>

<p>
  <b>Format:</b>
  <%= @sql_template.format %>
</p>

<p>
  <b>Locale:</b>
  <%= @sql_template.locale %>
</p>

<p>
  <b>Handler:</b>
  <%= @sql_template.handler %>
</p>

<p>
  <b>Partial:</b>
  <%= @sql_template.partial %>
</p>

<p>
  <b>Body:</b>
  <%= @sql_template.body %>
</p>

<%= link_to 'Edit', edit_sql_template_path(@sql_template) %> |
<%= link_to 'Back', sql_templates_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>